Feature/#76/boardRefactoring
KU-KUICS/KUICS_backend pull request #112
Opened 2020-09-03 08:29 UTC by lsjbh45

2020-09-03 08:35 UTC, Lanph3re approved these changes

2020-09-03 19:26 UTC, BeLeap requested changes

2020-09-03 19:26 UTC, BeLeap commented on src/api/boards/boards.ctrl.js
> +        const offset = (page - 1) * pageCount;
이거 pageCount가 아니라 count가 곱해져야 할 거 같은데?

2020-09-03 21:21 UTC, Lanph3re commented on src/api/boards/boards.ctrl.js
> +        const offset = (page - 1) * pageCount;
pageCount가 페이지당 게시글 수고 count는 그 페이지에서 가져올 게시글 수라서 pageCount 맞는 거 같은데?

2020-09-03 23:38 UTC, BeLeap commented on src/api/boards/boards.ctrl.js
> +        const offset = (page - 1) * pageCount;
ㄴㄴ 한페이지에 보이는 게시글 수는 프론트가 결정해야지 백에서 결정할게 아니지

2020-09-04 00:19 UTC, Lanph3re commented on src/api/boards/boards.ctrl.js
> +        const offset = (page - 1) * pageCount;
승직이 의도가 그렇다는 거지 ㅇㅇ

2020-09-09 01:17 UTC, lsjbh45 commented on src/api/boards/boards.ctrl.js
> +        const offset = (page - 1) * pageCount;
시작 offset은 pageCount를 곱하는게 맞지 않을까? pageCount가 한 페이지에 몇 개 씩인지를 나타내는거고 count가 그 offset부터 몇 개를 가져올지 나타내는 거니까 @BeLeap

2020-09-09 01:18 UTC, lsjbh45 commented on src/api/boards/boards.ctrl.js
> +        const offset = (page - 1) * pageCount;
프론트가 게시글 수를 결정하면 백에서 얼마나 보내줄지 어떻게 판단해야 하려나?

2020-09-09 01:19 UTC, BeLeap commented on src/api/boards/boards.ctrl.js
> +        const offset = (page - 1) * pageCount;
일단 내가 저거 처음에 설계했던 의도는 페이지당 예를들어 10개고 지금 2페이지 다를 프론트에서 넘기면
11번부터 10개 리턴하는거임

2020-09-09 01:19 UTC, BeLeap commented on src/api/boards/boards.ctrl.js
> +        const offset = (page - 1) * pageCount;
그리고 프론트가 크기에 따라 보여지는 개수가 바꿀 수 있게 프론트에서 인자로 받는게 맞다고 봄

2020-09-09 01:23 UTC, lsjbh45 commented on src/api/boards/boards.ctrl.js
> +        const offset = (page - 1) * pageCount;
그러면 예를 들어 31번째 글이면 10개씩 보여줄때는 4페이지에 나오고 15개씩 보여줄때는 3페이지에 나오고 이런식으로 하라는거지?

2020-09-09 01:23 UTC, lsjbh45 commented on src/api/boards/boards.ctrl.js
> +        const offset = (page - 1) * pageCount;
count하고 pageCount 통합해서

2020-09-09 01:24 UTC, BeLeap commented on src/api/boards/boards.ctrl.js
> +        const offset = (page - 1) * pageCount;
ㅇㅇ 그런말이지 그게 더 맞는거 같음

2020-09-09 01:26 UTC, lsjbh45 commented on src/api/boards/boards.ctrl.js
> +        const offset = (page - 1) * pageCount;
오키오키 수업 듣고 고쳐볼게

2020-09-09 04:02 UTC, lsjbh45 commented on src/api/boards/boards.ctrl.js
> +        const offset = (page - 1) * pageCount;
구현 변경 완료

2020-09-09 04:07 UTC, zheedong approved these changes

2020-09-14 13:07 UTC, BeLeap approved these changes

2020-09-14 14:09 UTC, merged