Feature/#15/notice
KU-KUICS/KUICS_backend pull request #115
Opened 2020-09-17 01:30 UTC by lsjbh45

2020-09-21 08:27 UTC, Lanph3re reviewed
고생 많았어~~

2020-09-21 08:27 UTC, Lanph3re commented on src/lib/validations.js
> +const checkAdmin = async (userId) => {
밑에 유저도 마찬가지고 Id만 email로 바꾸면 될 거 같고 함수 이름은 isAdmin, ...로 하자

2020-09-21 08:27 UTC, Lanph3re commented on src/api/admin/admin.ctrl.js
>  const isAdmin = async (email) => {
이건 지우고 위에 checkAdmin만 isAdmin으로 바꾸면 고칠 필요 없을듯

2020-09-21 08:27 UTC, Lanph3re commented on src/api/admin/admin.ctrl.js
> +        const admin = await checkAdmin(req.query.userId);
`const admin = await isAdmin(req.user.emails[0].value);`

2020-09-21 08:27 UTC, Lanph3re commented on src/lib/postingFunctions.js
> +/* TODO: 권한 확인 query, 데이터 요청 query 통합 */
관리자 API로 여기 들어오면 checkAdmin checkUser 두 번 하는데 그거 고친다는 TODO 맞아?

2020-09-21 08:27 UTC, Lanph3re commented on src/lib/postingFunctions.js
> +        const board = await checkBoard(boardId, type);
아마 boardId가 PK라서 type은 필요 없을것 같아

2020-09-21 08:27 UTC, Lanph3re commented on src/lib/postingFunctions.js
> +        await boards.update(
`boards.update()` 말고 위에서 board 룩업 한 번 해서 게시글 객체 갖고 있으니까 `board.update()` 이런 식으로도 됐던거같은데 성능 차이가 있는지 모르겠네. 심심할 때 알아보고 생각해봐 ㅋㅋ PK로 찾는 게 생략돼서 살짝 성능 좋아질 느낌인데

2020-09-21 08:27 UTC, Lanph3re commented on src/lib/postingFunctions.js
> +        if (!user) throw new Error('INVALID_PARAMETERS');
checkUser가 퀵스 회원인지 확인하는 함수로 알고 있는데 에러 메시지 NO_AUTH 돼야하는거 아닌가?

2020-09-21 08:27 UTC, Lanph3re commented on src/lib/postingFunctions.js
> +            /* attributes: [], */
토템인가!

2020-09-25 04:00 UTC, lsjbh45 commented on src/api/admin/admin.ctrl.js
>  const isAdmin = async (email) => {
그렇게 할 생각 ㅎㅎ

2020-09-25 04:02 UTC, lsjbh45 commented on src/api/admin/admin.ctrl.js
>  const isAdmin = async (email) => {
validation 이름을 다 check~~~로 만들어서 그렇게 하면 될 거 같음

2020-09-25 04:03 UTC, lsjbh45 commented on src/api/admin/admin.ctrl.js
> +        const admin = await checkAdmin(req.query.userId);
주석으로 남겨놔야겠다

2020-09-25 04:04 UTC, lsjbh45 commented on src/lib/validations.js
> +const checkAdmin = async (userId) => {
아 여기 있었네

2020-09-25 04:04 UTC, lsjbh45 commented on src/lib/validations.js
> +const checkAdmin = async (userId) => {
다 is~~~ 이걸로 바꾸는 게 나으려나?

2020-09-25 04:06 UTC, lsjbh45 commented on src/lib/postingFunctions.js
> +/* TODO: 권한 확인 query, 데이터 요청 query 통합 */
관리자 API에서 checkAdmin하는게 redundancy긴 한데 그렇게 체크해서 넘기는게 좀 더 안전할 거 같아서 일단 해놨어

저 TODO는 전에 validation 고쳤던 거 까먹고 안 지웠나보다

2020-09-25 04:10 UTC, lsjbh45 commented on src/lib/postingFunctions.js
> +        const board = await checkBoard(boardId, type);
checkBoard에 type 넣은 거는 함수 분리하면서 type 다른 걸로 요청 왔을 때 invalid 뜨게 하려고 일부러 이번에 추가한건데,

만약에 10번 글이 board인데 GET /api/notice/10으로 오면 글 안보여주도록 에러처리 하도록 만들었어
나머지 checkBoard 들어있는 부분도 그렇게 하니까 깔끔하게 type 일치 여부 체크되는거 같음

2020-09-25 04:13 UTC, lsjbh45 commented on src/lib/postingFunctions.js
> +        await boards.update(
checkboard가 board 전체를 반환하는게 아니라 지금은
`
        attributes: [
            ['userUserId', 'writerBoardId'],
            ['level', 'readLevel'],
        ],
`
이거 조건 줘서 attribute 이름 바꿔서 일부만 반환하도록 되어있거든
한 번 바꾸면 다 바꿔야 해서 될지는 모르겠는데 시도해볼게

2020-09-25 04:14 UTC, lsjbh45 commented on src/lib/postingFunctions.js
> +        if (!user) throw new Error('INVALID_PARAMETERS');
그거 창서가 굳이 그런 정보까지 알려줄 필요 없다고 해서 뺐었어

2020-09-25 04:19 UTC, lsjbh45 commented
@Lanph3re 리뷰 확인 완료~~
@zheedong @BeLeap 시간 될 때 #115 리뷰 부탁!!

2020-09-25 05:01 UTC, Lanph3re commented on src/lib/validations.js
> +const checkAdmin = async (userId) => {
리턴형이 Bool 느낌(checkAdmin 함수는 디비 객체긴 한데)인 함수들은 is...로 짓는게 흔한 스타일이니까? 더 직관적인거 같아서

2020-09-25 05:06 UTC, Lanph3re commented on src/lib/postingFunctions.js
> +        if (!user) throw new Error('INVALID_PARAMETERS');
얼핏 기억나는 것 같기도하네. 그런데 여기도 지금 보니까 userId말고 req.user(oauth 객체)에 있는 이메일로 유저 authentication 해야할 것 같네. 지금은 UserId랑 게시물 Id 알고 있으면 로그인 안해도 게시글 삭제 가능해보여

2020-09-25 05:10 UTC, Lanph3re commented on src/lib/postingFunctions.js
> +        const board = await checkBoard(boardId, type);
아하 오 굿

2020-09-25 05:13 UTC, lsjbh45 commented on src/lib/postingFunctions.js
> +        if (!user) throw new Error('INVALID_PARAMETERS');
checkUser도 나중에 다 이메일로 바꿔야지.. 이것도 validation lib쪽에 todo 남겨놨어

2020-09-25 05:16 UTC, lsjbh45 commented on src/lib/validations.js
> +const checkAdmin = async (userId) => {
checkBoard, checkComment 이런게 저번에 데이터 가져오는 부분이랑 통합해서 리턴형 좀 객체 느낌이 있긴 한데 어쨌든 이걸로 (!checkBoard) 이런식으로 쓰니까 is... 로 바꾸는게 나을 수도 있겠네

2020-09-25 05:24 UTC, lsjbh45 commented on src/lib/postingFunctions.js
> +        await boards.update(
이건 다른 attribute들 추가로 다 포함해도 가져올 때 `userUserId`, `level` attribute 이름 바꿔서 안 되는 거 같다 ㅠㅠ
저것들 `const { writerBoardId, readLevel } = board;` 이런식으로 validation에 쓰고 있어서 일단은 그냥 둬야 할 거 같네

2020-09-25 05:27 UTC, Lanph3re commented on src/lib/postingFunctions.js
> +        await boards.update(
어어 나도 확실친 않아서 ㅋㅋ 놔둬도 돼 ㅎㅎ

2020-09-25 05:27 UTC, Lanph3re commented on src/lib/postingFunctions.js
> +        if (!user) throw new Error('INVALID_PARAMETERS');
아하 오키

2020-09-26 06:41 UTC, BeLeap requested changes

2020-09-26 06:41 UTC, BeLeap commented on src/lib/postingFunctions.js
> +        next(err);
이 함수들은 next가 필요없을 거 같음 어짜피 바깥에 requestHandler들이 next로 error handling 해주니까 그냥 throw new Error만 해도 충분할듯 ㅇㅇ

2020-09-26 06:41 UTC, BeLeap commented on src/lib/postingFunctions.js
> +        const t = await sequelize.transaction();
https://github.com/KU-KUICS/KUICS_backend/pull/119#discussion_r495423333

2020-09-26 07:04 UTC, lsjbh45 commented on src/lib/validations.js
> +const checkAdmin = async (userId) => {
@BeLeap 이거 이름은 어떻게 짓는게 좋겠습니까?

2020-09-26 07:06 UTC, lsjbh45 commented on src/lib/postingFunctions.js
> +        next(err);
next 그냥 지워버리면 되나?

2020-09-26 07:07 UTC, BeLeap commented on src/lib/postingFunctions.js
> +        next(err);
ㅇㅇ 아마 그럴듯

2020-09-26 07:21 UTC, BeLeap commented on src/lib/validations.js
> +const checkAdmin = async (userId) => {
저는 is를 좋아합니다
ㅎㅎ

2020-09-26 07:24 UTC, lsjbh45 commented on src/lib/postingFunctions.js
> +        next(err);
선생님... next 안줬더니 `UnhandledPromiseRejectionWarning` 뜨면서 처리가 안되는데요?

2020-09-26 07:25 UTC, lsjbh45 commented on src/lib/postingFunctions.js
> +        const t = await sequelize.transaction();
[변경완료](https://github.com/KU-KUICS/KUICS_backend/pull/115/commits/4518709ed59c7c175133ab8e0564b97a425f1a13)

2020-09-26 07:27 UTC, lsjbh45 commented on src/lib/validations.js
> +const checkAdmin = async (userId) => {
그럼 is로 바꾸는걸로 하겠읍니다..

2020-09-26 07:29 UTC, BeLeap commented on src/lib/postingFunctions.js
> +        next(err);
음 그래요? 이상하네 안될게 없는뎀 내가 옛날에 그렇게 했던거 같은데 흠

2020-09-26 07:35 UTC, lsjbh45 commented on src/lib/validations.js
> +const checkAdmin = async (userId) => {
[변경완료](https://github.com/KU-KUICS/KUICS_backend/pull/115/commits/75de5217e638b56ec9a6e09943a520d2c870e113)

2020-09-26 07:37 UTC, lsjbh45 commented on src/lib/postingFunctions.js
> +        next(err);
throw로 다시 밖으로 넘겨도 안되는걸 보니 함수 안에서 처리를 안 하면 안되는듯 합니다

2020-09-26 07:38 UTC, BeLeap commented on src/lib/postingFunctions.js
> +        next(err);
ㅇㅎ 그렇군여 그럼 그대로 둡시당

2020-09-26 07:38 UTC, BeLeap commented
그럼 다 한건가요?

2020-09-26 07:40 UTC, lsjbh45 commented on src/lib/postingFunctions.js
> +        next(err);
ㅇㅎㅇㅎ next를 넘겨서 그런듯 하네요

2020-09-26 07:41 UTC, lsjbh45 commented on src/lib/postingFunctions.js
> +        next(err);
postingFunction에서 처리하는걸로 하고

2020-09-26 07:41 UTC, lsjbh45 commented on src/lib/postingFunctions.js
> +        next(err);
boards.ctrl하고 admin.ctrl하고 notice.ctrl에서 지워버리면 될 듯 합니다

2020-09-26 07:42 UTC, BeLeap commented on src/lib/postingFunctions.js
> +        next(err);
아 그렇군여 죠습니다

2020-09-26 07:45 UTC, lsjbh45 commented on src/lib/postingFunctions.js
> +        next(err);
[변경완료](https://github.com/KU-KUICS/KUICS_backend/pull/115/commits/2af528f1bbd93e3e56e7e65ed547b7359fa308d2)

2020-09-26 07:45 UTC, lsjbh45 commented
> 그럼 다 한건가요?

끝

2020-09-26 07:46 UTC, BeLeap approved these changes

2020-09-26 09:20 UTC, zheedong approved these changes

2020-09-26 09:20 UTC, merged