Feature/#88/ctf
KU-KUICS/KUICS_backend pull request #119
Opened 2020-09-23 05:18 UTC by Lanph3re

close #88

2020-09-25 04:25 UTC, lsjbh45 commented on src/api/challenge/challenge.ctrl.js
> +// TODO: 다른 API 멤버 체크 함수랑 통합
#115 머지하고 lib/validations.js에서 checkUser랑 합치면 될 거 같다

2020-09-25 04:31 UTC, lsjbh45 commented on src/models/attachedFiles.js
> +        AttachedFile.belongsTo(models.challenges);
이렇게 boards하고 challenges 둘 다 쓰이면 뭔가 문제 생길만한 거리는 없겠지?

2020-09-25 04:42 UTC, lsjbh45 commented on src/api/challenge/challenge.ctrl.js
> +            group: ['solvers.userUserId', 'user.userName'],
`solvers.userUserId`가 `user.userId`니까 이거 하나로만 그룹 하면 될 거 같은데, `user.userName`이 같이 들어간 이유가 있어? 만약 굳이 그룹 만들 때 user가 필요 없다면 model 3개 조인하는 것보다는 solvers, challenges 먼저 하고 결과랑 users 나중에 하는게 성능에 좋을 거 같아

2020-09-25 04:44 UTC, lsjbh45 commented on src/api/challenge/challenge.ctrl.js
> +            ],
여기서도 user는 푼 문제 각각 매칭할 필요 없이 userUserId 하나에만 맞추면 되니까 분리하는 게 좋을수도 있을 거 같네

2020-09-25 04:50 UTC, Lanph3re commented on src/models/attachedFiles.js
> +        AttachedFile.belongsTo(models.challenges);
음 아마..?

2020-09-25 04:53 UTC, Lanph3re commented on src/api/challenge/challenge.ctrl.js
> +            group: ['solvers.userUserId', 'user.userName'],
나도 `userId` 만 필요하다고 생각해서 처음에 그렇게 했는데 Postgres 특징인지 `userName` 넣어야 한다고 에러 뜨더라고..; 그리고 join 순서는 join이 피연산자 두 개 쓰는 연산이라 이미 너가 말한 순서대로 join 되는 걸로 알고 있어

2020-09-25 04:53 UTC, lsjbh45 commented on src/api/challenge/challenge.ctrl.js
> +        await t.commit();
트랜잭션에 `challenge.userUserId = checkMember.userId; // 퍼스트 블러드` 이 부분도 들어가야 할 듯!

2020-09-25 04:56 UTC, Lanph3re commented on src/api/challenge/challenge.ctrl.js
> +        await t.commit();
212라인 `await challenge.save({ transaction: t });`에 이미 들어가 있습니당

2020-09-25 04:58 UTC, lsjbh45 commented on src/api/challenge/challenge.ctrl.js
> +            group: ['solvers.userUserId', 'user.userName'],
음 그렇구만... ㅜㅜ

2020-09-25 04:59 UTC, Lanph3re commented on src/api/challenge/challenge.ctrl.js
> +            ],
이거 쿼리 결과가 푼 문제 row들이 반환되는 거라서 `userName`을 따로 한 번만 받는 방법이 생각이 안나더라고. userId로 유저 테이블에 쿼리를 따로 날리는 방법 정도 생각이 나는데 다른 좋은 방법 있나?

2020-09-25 05:01 UTC, lsjbh45 commented on src/api/admin/admin.ctrl.js
> +
파일 올리는 부분 board에서도 공유해서 쓸 수 있게 lib로 뺄 수 있으려나?

2020-09-25 05:03 UTC, lsjbh45 commented on src/api/challenge/challenge.ctrl.js
> +            ],
따로 날리는 게 더 괜찮을 거 같긴 한데.. 한 사람이 푼 거니까 각 문제에 `userName`이 붙으면 더 이상하지 않으려나?

2020-09-25 05:04 UTC, lsjbh45 commented on src/api/challenge/challenge.ctrl.js
> +        await t.commit();
트랜잭션 선언을 하기 전에 바꾼 부분도 들어가는군요.. 하나 배워갑니다

2020-09-25 05:06 UTC, lsjbh45 commented on src/api/admin/admin.ctrl.js
> +
putChallenge에도 쓰니까 빼 두면 좋을 거 같긴 하네

2020-09-25 05:08 UTC, lsjbh45 commented on src/api/admin/admin.ctrl.js
> +
challenge는 지우면 숨기는게 아니라 아예 삭제되는 식으로 가는건가? cascade 했으니까 solver같은 부분도 없어질 거 같은데 의도된거지?

2020-09-25 05:08 UTC, lsjbh45 commented on src/api/admin/admin.ctrl.js
>  };
admin.ctrl.js #115 랑 conflict 날 느낌인데 merge 전에 한 번 확인해주세요

2020-09-25 05:12 UTC, Lanph3re commented on src/api/challenge/challenge.ctrl.js
> +            ],
ㅋㅋㅋㅋㅋㅋㅋ 그러게 이상하긴 하지... 따로 한다고 뭐 크게 차이 안나겠지 ㅇㅋ 고쳐서 커밋할게

2020-09-25 05:15 UTC, Lanph3re commented on src/api/admin/admin.ctrl.js
> +
음... 너 pr이랑 이거랑 둘 다 머지되고 나면 생각해보자 ㅇㅇㅇㅇ 코드는 읽어둬

2020-09-25 05:16 UTC, Lanph3re commented on src/api/admin/admin.ctrl.js
> +
어어 지우면 solver까지 지워져야하고 이거 삭제해보니까 저번에 얼핏 너가 얘기했던 거처럼 실제 row가 없어지는 건 아니고 deletedAt 필드 설정되던데?

2020-09-25 05:18 UTC, lsjbh45 commented on src/api/admin/admin.ctrl.js
> +
굿굿!! 안그래도 파일을 어떻게 넣을까 했는데 ㅎㅎ

2020-09-25 05:18 UTC, Lanph3re commented on src/api/admin/admin.ctrl.js
>  };
아마 문제 없을 거야 ㅋㅋ 확인할게

2020-09-25 05:19 UTC, lsjbh45 commented on src/api/admin/admin.ctrl.js
> +
아 그래? paranoid 옵션이 default로 들어가는구나

2020-09-25 05:25 UTC, Lanph3re commented on src/api/challenge/challenge.ctrl.js
> +            ],
fcf8611a7a00774e46495eb7f791c5f446e26160 에 수정 완료

2020-09-25 05:26 UTC, lsjbh45 approved these changes
👍👍👍

2020-09-26 06:29 UTC, BeLeap commented on src/api/challenge/challenge.ctrl.js
> +            raw: true,
raw: true는 왜 있는거임?

2020-09-26 06:31 UTC, BeLeap commented on src/api/challenge/challenge.ctrl.js
> +            raw: true,
raw:true가 왜 있는거임?

2020-09-26 06:31 UTC, BeLeap commented on src/api/challenge/challenge.ctrl.js
> +        const t = sequelize.transaction();
transcationalManager안쓰고 이렇게 한 이유가 있음?

2020-09-26 06:32 UTC, BeLeap requested changes
확인해주세여

2020-09-26 06:39 UTC, BeLeap commented on src/api/challenge/challenge.ctrl.js
> +        const t = sequelize.transaction();
try {

  const result = await sequelize.transaction(async (t) => {

    const user = await User.create({
      firstName: 'Abraham',
      lastName: 'Lincoln'
    }, { transaction: t });

    await user.setShooter({
      firstName: 'John',
      lastName: 'Boothe'
    }, { transaction: t });

    return user;

  });

  // If the execution reaches this line, the transaction has been committed successfully
  // `result` is whatever was returned from the transaction callback (the `user`, in this case)

} catch (error) {

  // If the execution reaches this line, an error occurred.
  // The transaction has already been rolled back automatically by Sequelize!

}
이런거도 있거든 ㅇㅇ

2020-09-26 06:42 UTC, Lanph3re commented on src/api/challenge/challenge.ctrl.js
> +            raw: true,
저거 없으면 안되는거같던데 정확힌 모르겠다

2020-09-26 06:43 UTC, Lanph3re commented on src/api/challenge/challenge.ctrl.js
> +        const t = sequelize.transaction();
승직이거 보고 그냥 따라 쓴 건데 너가 알려준게 깔끔한가?

2020-09-26 06:44 UTC, BeLeap commented on src/api/challenge/challenge.ctrl.js
> +            raw: true,
음 그래? 저거 들어간 데이터를 사용하는게 아니면 없어도 되는거일거 같은데

2020-09-26 06:44 UTC, BeLeap commented on src/api/challenge/challenge.ctrl.js
> +        const t = sequelize.transaction();
모르겠음 뭐 적당히 뭐가 좋은지는 생각하기 나름이지 승직이랑도 얘기해봐야할듯 ㅇㅇ

2020-09-26 07:09 UTC, lsjbh45 commented on src/api/challenge/challenge.ctrl.js
> +            raw: true,
raw: true 안 하면 json에 다른 정보들 딸려 들어와서

2020-09-29 10:20 UTC, BeLeap approved these changes

2020-09-30 07:59 UTC, closed without merging