Feature/#16/boards
KU-KUICS/KUICS_backend pull request #87
Opened 2020-07-18 04:10 UTC by lsjbh45

2020-07-18 07:21 UTC, BeLeap commented on src/api/boards/boards.ctrl.js
> + *  @group Board
parameter도 추가해주시죠

2020-07-18 07:54 UTC, BeLeap commented on src/api/boards/boards.ctrl.js
> + *  @group Board
여기도 마찬가지로 param 추가해주세요

2020-07-18 08:41 UTC, BeLeap requested changes

2020-07-18 08:41 UTC, BeLeap commented on src/api/boards/boards.ctrl.js
> +        const checkExists = await existsBoard(boardId);
변수명을 exits로 하는게 더 의미를 잘 전달할 것 같습니다. 밑으로도 마찬가지

2020-07-18 08:41 UTC, BeLeap commented on src/api/boards/boards.ctrl.js
> +        }
유저 체크하는 로직을 나중에 갈아엎으면 비교연산자를 이용해서 구현하는 것이 나을 것 같습니다.
일단 지금은 스킵

2020-07-18 08:41 UTC, BeLeap commented on src/api/boards/boards.ctrl.js
> +        const boardList = await boards.findOne({
findOne인데 왜 boardList인거죠?

2020-07-18 08:41 UTC, BeLeap commented on src/api/boards/boards.ctrl.js
> +                'type',
어짜피 type은 다 board니 굳이 가져올거 없어보입니다.

2020-07-18 08:41 UTC, BeLeap commented on src/api/boards/boards.ctrl.js
> +                'excerpt',
상세보기 창이니 요약도 필요없을 거 같습니다.

2020-07-18 08:41 UTC, BeLeap commented on src/api/boards/boards.ctrl.js
> + *  @group Board
@param 추가해주세요

2020-07-18 08:41 UTC, BeLeap commented on src/api/boards/boards.ctrl.js
> +            { where: { boardNo: boardId } },
type이 board인지 확인해서 notice를 수정하고 있는 것은 아닌지 확인이 필요해보입니다.

2020-07-18 08:41 UTC, BeLeap commented on src/api/boards/boards.ctrl.js
> +        await boards.destroy({ where: { boardNo: boardId } });
여기도 type을 확인해서 notice를 삭제하는 것을 방지해야할 것 같습니다.

2020-07-18 08:41 UTC, BeLeap commented on src/api/boards/boards.ctrl.js
> +            throw new Error('DELETED');
회의에서 말했듯이 굳이 유저에게 DELETED라는 정보를 줄 이유가 없습니다.
INVALID_PARAMETER로 수정하는게 좋아보입니다.

2020-07-18 08:41 UTC, BeLeap commented on src/api/boards/boards.ctrl.js
> + *  @param {commentScheme.model} commentScheme.body.required - 작성할 댓글 정보
commentScheme은 Joi에 있는거 아닌가요
이걸 왜 여기서...

2020-07-18 08:41 UTC, BeLeap commented on src/api/boards/boards.ctrl.js
> +            commentsNo: commentCount + 1,
pk에 autoincrement쓰면 안되나요?

2020-07-18 08:41 UTC, BeLeap commented on src/api/boards/boards.ctrl.js
> +            });
여기서 만들고 increment할때 transaction을 적용해야할거 같습니다.
밑에 destory할 때와 recommend 처리할 때도 마찬가지입니다.

2020-07-18 09:36 UTC, lsjbh45 commented on src/api/boards/boards.ctrl.js
> +        const checkExists = await existsBoard(boardId);
이건 밑에 existsBoard, existComment로 하면 함수하고 이름 겹쳐서 안되길래 check 다 붙여서 썼음

2020-07-18 09:51 UTC, lsjbh45 commented on src/api/boards/boards.ctrl.js
> +            commentsNo: commentCount + 1,
commentsNo pk 아님

2020-07-18 10:06 UTC, lsjbh45 commented on src/api/boards/boards.ctrl.js
> + *  @param {commentScheme.model} commentScheme.body.required - 작성할 댓글 정보
body로 넘어오는 parameter

2020-07-18 10:07 UTC, lsjbh45 commented on src/api/boards/boards.ctrl.js
> + *  @param {commentScheme.model} commentScheme.body.required - 작성할 댓글 정보
이름을 commentScheme으로 붙여서 헷갈린듯?

2020-07-18 10:12 UTC, lsjbh45 commented on src/api/boards/boards.ctrl.js
> +                'type',
가져오는건 일단 임시

2020-07-18 10:45 UTC, BeLeap commented on src/api/boards/boards.ctrl.js
> + *  @param {commentScheme.model} commentScheme.body.required - 작성할 댓글 정보
? typedef 없던데

2020-07-18 10:45 UTC, BeLeap commented on src/api/boards/boards.ctrl.js
> +            commentsNo: commentCount + 1,
pk 아니어도 autoincrement 됨

2020-07-19 11:18 UTC, lsjbh45 commented on src/api/boards/boards.ctrl.js
> +            commentsNo: commentCount + 1,
commentsNo 이거 지금 잘못 붙여서 수정할 예정

2020-07-19 11:22 UTC, lsjbh45 commented on src/api/boards/boards.ctrl.js
> +            { where: { boardNo: boardId } },
notice는 writer가 admin일텐데 writer와 userId가 같은지 체크하는 isWriterBoard로 충분하지 않을까?

2020-07-19 11:24 UTC, lsjbh45 commented on src/api/boards/boards.ctrl.js
> +            { where: { boardNo: boardId } },
아 그냥 update에서 체크하면 별로 비싸지 않으니까 그냥 넣어도 되겠네

2020-07-19 11:32 UTC, lsjbh45 commented on src/api/boards/boards.ctrl.js
> + *  @param {commentScheme.model} commentScheme.body.required - 작성할 댓글 정보
위에 있는디??

2020-07-19 13:55 UTC, lsjbh45 commented on src/api/boards/boards.ctrl.js
> +        const checkExists = await existsBoard(boardId);
요거는 권한 확인 바꾸면서 naming 완료

2020-07-19 13:56 UTC, lsjbh45 commented on src/api/boards/boards.ctrl.js
> +        }
구현 완료

2020-07-20 03:57 UTC, Lanph3re requested changes

2020-07-20 03:57 UTC, Lanph3re commented on src/api/boards/boards.ctrl.js
> +            where: { type: 'board', boardNo: boardId },
boardNo가 PK라서 type 조건은 불필요한듯

2020-07-20 03:57 UTC, Lanph3re commented on src/api/boards/boards.ctrl.js
> +            where: { type: 'board', boardNo: boardId },
그리고 저번에 얘기한 거랑 똑같은 건데 checkBoard에서 board 테이블 쿼리하고 `const boardList = await boards.findOne(...)`에서 쿼리 또 하는 거니까 합치면 좋을 것 같당. 아래쪽에도 똑같은 코드 많아서 전부 한 번 생각해보고
아마 checkBoard할 때 가져올 attributes 인자로 받게 하면 될 거 같은데

2020-07-20 03:57 UTC, Lanph3re commented on src/api/boards/boards.ctrl.js
> +        const isWriterBoard = userNo === writerBoardNo;
생각해보니까 이 조건을 DB 쿼리할 때 같이 넣어주면 이 라인이랑 이 바로 다음 라인 없어도 될 거 같은데 어떻게 생각해

2020-07-20 03:57 UTC, Lanph3re commented on src/api/boards/boards.ctrl.js
> +        const writeAuth = level <= userLevel;
자기가 썼던 건데 권한이 달라질 일이 있으려나

2020-07-20 04:11 UTC, lsjbh45 commented on src/api/boards/boards.ctrl.js
> +        const isWriterBoard = userNo === writerBoardNo;
isWriterBoard 요거 체크는 reviseBoard하고 deleteBoard에만 쓰는거고 쿼리에 넣으려면 userNo도 넣어줘야 할거 같아서 그냥 API 안에다 넣었어

2020-07-20 04:11 UTC, lsjbh45 commented on src/api/boards/boards.ctrl.js
> +        const isWriterBoard = userNo === writerBoardNo;
그냥 === 확인만 하는 거니까 성능 차이는 별로 없지 않을까?

2020-07-20 04:13 UTC, lsjbh45 commented on src/api/boards/boards.ctrl.js
> +            where: { type: 'board', boardNo: boardId },
아 그렇지 type은 뺄게

2020-07-20 04:14 UTC, lsjbh45 commented on src/api/boards/boards.ctrl.js
> +            where: { type: 'board', boardNo: boardId },
일단 권한 확인하는건 쿼리 통일하긴 했는데 데이터 가져오는 쿼리하고도 겹치네.. 이건 다시 보고 고치는걸로 할게

2020-07-20 04:15 UTC, lsjbh45 commented on src/api/boards/boards.ctrl.js
> +            where: { type: 'board', boardNo: boardId },
attribute 전부 가져와서 필요한거만 쓰면 될 거 같긴 한데

2020-07-20 04:50 UTC, Lanph3re commented on src/api/boards/boards.ctrl.js
> +        const isWriterBoard = userNo === writerBoardNo;
ㅇㅇ 별 차이 없을거같긴해 ㅋㅋ 편한대로

2020-07-20 04:51 UTC, Lanph3re commented on src/api/boards/boards.ctrl.js
> +            where: { type: 'board', boardNo: boardId },
type 빼야하는 거 여러 개 있어 확인좀~

2020-07-20 16:08 UTC, BeLeap commented on src/api/boards/boards.ctrl.js
> + *  @param {commentScheme.model} commentScheme.body.required - 작성할 댓글 정보
아 그러네 ㅈㅅ합니다

2020-07-20 16:13 UTC, BeLeap commented on src/api/boards/boards.ctrl.js
> +        const boardList = await boards.findOne({
이거 그냥 두기로 한건가여?
머 안바꿔도 괜찮다고 생각하면 안바꿔도 됩니다.
말그대로 추천이라 ㅇㅇ

2020-07-20 16:14 UTC, BeLeap commented on src/api/boards/boards.ctrl.js
> +        const boardData = await boards.findAll({
여기 findOne이 맞지 않나여

2020-07-21 01:23 UTC, lsjbh45 commented on src/api/boards/boards.ctrl.js
> +        const boardList = await boards.findOne({
내용물만 바꾸고 이름을 안바꿨군요

2020-07-21 01:24 UTC, lsjbh45 commented on src/api/boards/boards.ctrl.js
> +        const boardData = await boards.findAll({
맞네요

2020-07-26 13:15 UTC, BeLeap approved these changes

2020-07-27 01:27 UTC, Lanph3re approved these changes

2020-07-27 11:20 UTC, zheedong approved these changes

2020-07-27 11:25 UTC, merged