상세 검색 구현
KU-KUICS/KUICS_backend pull request #97
Opened 2020-08-08 03:43 UTC by zheedong

2020-08-08 05:12 UTC, lsjbh45 approved these changes

2020-08-09 07:34 UTC, Lanph3re approved these changes

2020-08-14 07:30 UTC, BeLeap commented
이거 where에서 Op.or 말고 array 쓰면 되는거같던데 한번 확인해주시죠

2020-08-14 07:33 UTC, BeLeap requested changes
머 알아봐주시져

2020-09-20 08:46 UTC, merged